#!/bin/sh
export ADDED="BLOCK_SLOTS,CRANE_SLOT,BLOCK_HANGING,BLOCK_DROPPED,BLOCK_RETURNING,BLOCK_LANDED,BLOCK_TUMBLING,BLOCK_ROPE_LOWERING,BLOCK_DEBRIS_WAITING,PHASE_PLAYING,PHASE_ROOF,PHASE_ROUND_OVER,PHASE_RESULT,PHASE_INTRO,GAME_MODE_CITY_TOWER,GAME_MODE_QUICK,ANGLE_NONE,ANGLE_RETURNING,LOST_SCREEN_X,LOST_TIME,ROTATION_EASE_MS,GRAVITY_DIVISOR,GRAVITY_DIVISOR_ROOF,MAX_FALL_PER_FRAME,RETURN_SPEED,RETURN_STOP_BELOW_TOP,REHANG_DELAY_MS,FULL_ROPE_LENGTH,easeAngle"
export EXCL="House::updateBlockPhysics"
exec python3 /tmp/w/bccheck.py "$@"
